### ISSUE TITLE
[FIX] 성적 입력 시 이전 입력 데이터의 이름이 뜨지 않고 과목선택만 뜸.(이미지확인)

### ISSUE THREAD

**Issue by daeGULLL** [kimleeoh/Front#14]
![Image](https://github.com/user-attachments/assets/ab7b503f-3aa2-411a-bf35-8a3ee6223d96)
![Image](https://github.com/user-attachments/assets/b5c023a0-5b4c-46ef-93d4-3caf63c5f82b)

이미 입력된 과목이 저래 뜸 해결 방법이 있을까요?

**Comment by seulnan** [comment]
그게무슨말이져...

**Comment by seulnan** [comment]
영상이나 플로우로 설명가능할까요?
ex)
보니까 과정이 이러함
계정 a로 로그인했을때 계정 a정보뜸
-> 로그아웃하고 계정 b로 로그인함
-> 프로필 api호출자체가 안됨. 그래서 브라우저에 원래있던값인 계정 a정보가 뜸
-> 새로고침해야 프로필 api호출이되고 계정b 정보가 렌더링됨

이런식으로설명부탁드려용 연서가 뭘추가했는데 이렇게 떴다 이런거

**Comment by daeGULLL** [comment]
ex) 성적 등록하기 요청을 2024 1학기에 함, 승인받음 -> 성적 등록하기 재접속, 2024 1학기 선택 시 기존에 입력했던 성적이 성적명이 뜨지 않고 과목선택 드롭다운만 뜸.

**Comment by seulnan** [comment]
아근데 굳이 그 원래등록해뒀던과목들을 띄울 필요가 없다생각함
이유
1. 일단 너무 불필요한 서버한테 요청하게됨 (드롭다운선택할때도 api호출을 보내서 이미 등록된건지 안된건지 확인하고 맞다면 그걸 불러와야함)
2. 그걸 처리하는데도 리액트쪽 과부하가 올 가능성이 있음
3. 무엇보다 사용자 flow가 그렇게 흘러가지않을것같음 
내가 예상한 사용자 flow 
24년도 1학기에 a과목, b과목, c과목 인증하려시도
-> a과목 & b과목은 인증을 받았ㅇ나 c과목 오타로 인해 인증반려됨 
-> 그럼 백에서는 a,b 만 인증하고 c는 인증안된상태로 메인성적창에 띄움
-> 근데 사용자가 생각해보니 d과목을 빼놓고 인증함 
-> 그럼 굳이 24년도 1학기때 이미 인증한 a,b과목을 인증창에서도 띄울필요없이 그냥 인증해야하는 c과목과 d과목만 추가적으로 등록하면됨
-> 그럼 걍 서버에서도 추가데이터인 c와 d만 처리하면 됨

**Comment by daeGULLL** [comment]
그리고 저게 그냥 빈 과목선택이 뜬다는게 아니라 이전에 입력했던 성적이 저렇게 자동으로 성적 등록하기 누르면 떠지는 상태인거임. 만약 내가 이전에 a학기에 과목 2개 인증해놓고 다시 a학기 성적 등록하기 접속시 저 과목선택 열이 2개가 나타남. 

c과목이 승인안된상태면 그걸 성적입력창에서 다시 선택해야하는거임? 그러면 사용자한테 다시 입력하세요라고 보여줘야할듯. 안그러면 대부분 반려되면 그대로 들어가서 성적만 바꾸려고 할텐데 아무것도 안뜨면 당황할테니?

**Comment by seulnan** [comment]
그거는 성적메인창에서 c과목은 인증되지않았다가 뜰거임 (동현이한테 구현부탁햇는데아직안한듯)
그니까 a,b는인증됨 이 옆에 뜨고 c는 안뜨니까 사용자가 걍 다시 등록해야지
너말대로 빈과목선택이 뜬다는거말고 이전에 입력했던 성적이 자동으로 뜨게해라인걸로 이해하고 저 3가지이유를 댄거임
굳이 뜨게 할이유가 없고 구현할때 불필요한 소스가 너무 들어감

**Comment by daeGULLL** [comment]
인증표시 없으면 다시 입력하세요라는 것을 알릴 방법이 있는게 좋을듯.

그리고 이전에 입력했던 성적이 이미 자동으로 뜨는 상태긴 함. 입력한 과목명도 전달이 되긴 함. 그래서 이 부분을 그냥 아예 없애버리는것보단 placeholder같은거로 드롭다운에 넣으면 안되려나..? 그리고

**Comment by daeGULLL** [comment]
내가 해결해벌임
