### ISSUE TITLE
[BUG] mypage에서 예전계정정보로 뜸

### ISSUE THREAD

**Issue by seulnan** [kimleeoh/Front#9]
로그아웃을 했는데도 오류가 뜨는줄알았는데
보니까 과정이 이러함 
 계정 a로 로그인했을때 계정 a정보뜸
-> 로그아웃하고 계정 b로 로그인함
-> 프로필 api호출자체가 안됨. 그래서 브라우저에 원래있던값인 계정 a정보가 뜸
-> 새로고침해야 프로필 api호출이되고 계정b 정보가 렌더링됨

로그아웃했다가 다른계정으로 들어갈때 왜 api호출이안되지...?

**Comment by Second-FirstKiss** [comment]
UserContext 에 setUserData를 외부에서 접근할 수 있게 수정해서 메뉴페이지에서 로그아웃 버튼을 눌렀을 때 UserData를 null로 설정해서 이전 계정 정보가 뜨는 문제 해결 완료

**Comment by seulnan** [comment]
근데 그 배포환경에서도 잘 되는지 봐야하는데 아직 그 자동화구축이 덜되어서 확인불가..

**Comment by seulnan** [comment]
해결완료된거 확인
